/**
 * UI text catalog: Simplified Chinese (default, and always in the China
 * build) and English. `T` and the name tables are mutable objects that
 * `setLocale` refills, so components keep importing them directly; the app
 * root remounts its tree when the language changes.
 */
import type { Pattern, Suit } from '@mahjong/engine';

export type Locale = 'zh' | 'en';

const zhNames = {
  suits: { 0: '万', 1: '条', 2: '筒' } as Record<Suit, string>,
  /** Short suit mark printed on tile faces. */
  tileSuits: { 0: '万', 1: '条', 2: '筒' } as Record<Suit, string>,
  ranks: ['一', '二', '三', '四', '五', '六', '七', '八', '九'],
  patterns: {
    pingHu: '平胡',
    duiDuiHu: '对对胡',
    qingYiSe: '清一色',
    qiDui: '七对',
    jinGouDiao: '金钩钓',
    jiangDui: '将对',
    qingDui: '清对',
    longQiDui: '龙七对',
    qingQiDui: '清七对',
    qingLongQiDui: '清龙七对',
    gen: '根',
    gangShangHua: '杠上花',
    gangShangPao: '杠上炮',
    qiangGang: '抢杠胡',
    haiDi: '海底捞月',
    ziMo: '自摸',
    tianHu: '天胡',
    diHu: '地胡',
  } as Record<Pattern, string>,
  payments: {
    win: '胡牌',
    directKong: '直杠',
    addedKong: '补杠',
    concealedKong: '暗杠',
    callTransfer: '呼叫转移',
    huaZhu: '查花猪',
    daJiao: '查大叫',
    kongRefund: '退税',
  } as Record<string, string>,
};

const enNames: typeof zhNames = {
  suits: { 0: 'Characters', 1: 'Bamboo', 2: 'Dots' },
  tileSuits: { 0: 'Crak', 1: 'Bam', 2: 'Dot' },
  ranks: ['1', '2', '3', '4', '5', '6', '7', '8', '9'],
  patterns: {
    pingHu: 'Plain Win',
    duiDuiHu: 'All Pongs',
    qingYiSe: 'Pure Suit',
    qiDui: 'Seven Pairs',
    jinGouDiao: 'Golden Hook',
    jiangDui: '2-5-8 Pongs',
    qingDui: 'Pure All Pongs',
    longQiDui: 'Dragon Seven Pairs',
    qingQiDui: 'Pure Seven Pairs',
    qingLongQiDui: 'Pure Dragon Seven Pairs',
    gen: 'Root',
    gangShangHua: 'Win on Kong Draw',
    gangShangPao: 'Win on Kong Discard',
    qiangGang: 'Robbing the Kong',
    haiDi: 'Last Tile Win',
    ziMo: 'Self-Draw',
    tianHu: 'Heavenly Hand',
    diHu: 'Earthly Hand',
  },
  payments: {
    win: 'Win',
    directKong: 'Exposed Kong',
    addedKong: 'Added Kong',
    concealedKong: 'Concealed Kong',
    callTransfer: 'Kong Transfer',
    huaZhu: 'Flower Pig',
    daJiao: 'Not Ready',
    kongRefund: 'Kong Refund',
  },
};

const zh = {
  appTitle: '四川麻将 · 血战到底',
  start: '开始游戏',
  hands: '局数',
  baseScore: '底分',
  connecting: '正在连接服务器…',
  offline: '无法连接服务器，正在重试…',
  reconnecting: '正在重新连接…',
  swapHint: '已按建议选好三张，可点牌改选（须同一花色）',
  swapConfirm: '确认换牌',
  swapWaiting: '等待其他玩家换牌…',
  dingqueHint: '选择要打缺的花色',
  dingqueWaiting: '等待其他玩家定缺…',
  voidSuit: (suit: string) => `缺${suit}`,
  tileShort: (rank: number, suit: string) => `${rank}${suit}`,
  pong: '碰',
  kong: '杠',
  hu: '胡',
  zimo: '自摸',
  pass: '过',
  discard: '出牌',
  discardHint: '点两次出牌，或上滑',
  voidFirst: '请先打完缺门牌',
  autoPlayOn: '托管中 — 点击取回控制',
  autoPlay: '托管',
  skipToResults: '跳过，直接看结算',
  leave: '离开',
  leaveConfirmTitle: '离开牌局？',
  leaveConfirmBody: '离开后由系统托管打完本局，结算照常进行。',
  cancel: '取消',
  confirm: '确定',
  wall: '剩余',
  dealer: '庄',
  tilesInHand: (n: number) => `${n}张`,
  robbed: '被抢杠!',
  handResult: '本局结算',
  gameResult: '整场结算',
  nextHand: '下一局',
  newGame: '再来一场',
  backHome: '返回大厅',
  threeWon: '三家胡牌',
  wallExhausted: '流局',
  huaZhu: '花猪',
  ready: '听牌',
  notReady: '未听',
  me: '（我）',
  dealtInBy: (name: string) => `（${name} 点炮）`,
  fan: (n: number) => `${n} 番`,
  colon: '：',
  listSeparator: '　',
  hand: (i: number, n: number) => `第 ${i + 1} / ${n} 局`,
  swapDirection: { clockwise: '顺时针换牌', counterClockwise: '逆时针换牌', opposite: '对家换牌' } as Record<string, string>,
  timeoutWarning: (s: number) => `${s} 秒后将自动出牌`,
  waiting: '听',
  discardedBy: (name: string) => `${name} 打出`,
  waitingNone: '已听牌，但要的牌都已出完',
  tilesLeft: (n: number) => `剩 ${n} 张`,
  ifDiscard: '打出后',
  shantenAfter: (n: number) => `还差 ${n} 张才听牌`,
  hint: '💡 提示',
  hintClaim: (what: string) => `建议：${what}`,
  tracker: '记牌',
  record: {
    entry: '战绩',
    title: '战绩与回放',
    games: '场数',
    hands: '局数',
    winRate: '胡牌率',
    selfDraws: '自摸',
    dealInRate: '点炮率',
    bestFan: '最大番数',
    recent: '最近的牌局（点一局看回放）',
    regulars: '牌友',
    regularsHint: '和你同桌过的 AI 角色',
    together: (hands: number) => `同桌 ${hands} 局`,
    headToHead: (mine: number, theirs: number) => `你胡 ${mine} 次 · TA 胡 ${theirs} 次`,
    dealIns: (mine: number, theirs: number) => `你点 TA ${mine} 炮 · TA 点你 ${theirs} 炮`,
    bond: (hands: number, rival: boolean): string => (rival ? '死对头' : hands >= 40 ? '老牌友' : hands >= 8 ? '熟人' : '新面孔'),
    empty: '还没有打完的牌局',
    won: (fan: number, selfDraw: boolean) => `${selfDraw ? '自摸' : '胡'} ${fan} 番`,
    handOf: (i: number) => `第 ${i + 1} 局`,
    back: '返回',
    loadFailed: '加载失败，请稍后再试',
  },
  bindReminder: {
    text: '游客账号换手机或清除数据后，金币、段位和成就都会丢失。绑定一个登录方式就能保住进度。',
    bind: '去绑定',
    later: '以后再说',
  },
  fairness: {
    verified: '🔒 发牌已验证：开局前锁定，全程未改动',
    failed: '⚠️ 发牌校验没通过，请联系客服',
    details: '查看校验数据',
    hide: '收起',
    commitment: (c: string) => `开局前公布的摘要：${c}`,
    revealed: (seed: number, salt: string) => `本局公开的种子：${seed} · ${salt}`,
    how: '开局前我们公布 sha256(种子:随机串) 的摘要，结束后公开种子。用种子能重新发出整副牌，和摘要对得上，就说明发牌在开局前就定好了，中途没有改动。',
    replay: (seed: number) => `🔒 这一局由种子 ${seed} 发牌，回放就是用它重新发出来的`,
  },
  rank: {
    tiers: { novice: '雀士', adept: '雀杰', expert: '雀豪', master: '雀圣', saint: '雀神' } as Record<string, string>,
    label: (tier: string, points: number) => `${tier} · ${points} 分`,
    toNext: (n: number) => `再得 ${n} 分升段`,
    result: (place: number, change: number) => `第 ${place} 名 · 段位分 ${change >= 0 ? '+' : ''}${change}`,
    promoted: (tier: string) => `升段！成为 ${tier}`,
    note: '只有初级场及以上的金币场计入段位',
  },
  friend: {
    entry: '好友房',
    hint: '和朋友一起打，只算分不算金币',
    title: '好友房',
    intro: '和朋友坐一桌，只算分、不算金币，也不计段位。坐不满 4 人时由 AI 补位。',
    createTitle: '开一个房间',
    create: '创建',
    joinTitle: '输入朋友的房号',
    join: '加入',
    waitingTitle: '等朋友入座',
    roomNumber: '房号',
    shareHint: '分享邀请链接，朋友点开就能进来；也可以把房号告诉他',
    aiFill: 'AI 补位',
    host: '房主',
    offline: '离线',
    rules: (hands: number, mode: string) => `${mode} · ${hands} 局 · 只算分不算金币 · 空位由 AI 补上`,
    leave: '离开房间',
    start: '开始游戏',
    startWithAi: 'AI 补位开始',
    startJustUs: (n: number) => `就我们 ${n} 个打（两房）`,
    needFriend: '等朋友加入',
    waitingHost: '等房主开始…',
    tableName: '好友房',
    readyWaiting: '已准备，等其他玩家…',
    share: '📤 分享邀请',
    copied: '邀请已复制，粘贴给朋友就行',
    shareFailed: '没能打开分享，请把房号告诉朋友',
    inviteText: (code: string, url: string) => `来四川麻将好友房一起打牌！房号 ${code}
点链接直接加入：${url}`,
    rejected: {
      notFound: '没有这个房号，请核对一下',
      full: '房间已经坐满了',
      inGame: '你正在牌局中，先打完这一场',
      notHost: '只有房主能开始',
      needFriend: '至少要有一位朋友加入才能开始',
      blocked: (name: string) => `${name} 现在不能开始游戏（游戏时间限制或实名认证）`,
    } as Record<string, string | ((name: string) => string)>,
  },
  achievements: {
    entry: '成就',
    title: '成就',
    intro: '打牌自然会解锁，奖励自动到账，不用做任务，也不用每天来领。',
    loginTitle: '每日登录奖励（每天第一次打开自动到账）',
    listTitle: '成就（每个奖励一次）',
    claim: (n: number) => `领取 ${n}`,
    earned: (names: string, total: number) => `🏆 ${names}　🪙 +${total}`,
    paid: '已到账',
    locked: '未达成',
    names: {
      login: '今日登录奖励',
      firstWin: '第一次胡牌',
      firstSelfDraw: '第一次自摸',
      firstKong: '第一次开杠',
      duiDuiHu: '胡一次对对胡',
      qiDui: '胡一次七对',
      qingYiSe: '胡一次清一色',
      gangShangHua: '杠上开花',
      bigWin: '一把胡 3 番以上',
      wins10: '累计胡牌 10 次',
      wins50: '累计胡牌 50 次',
      games10: '打完 10 场',
    } as Record<string, string>,
  },
  settings: {
    entry: '设置',
    title: '设置',
    fastPace: '快速模式',
    fastPaceHint: 'AI 出牌几乎不停顿，节奏更快',
    voice: '语音播报碰、杠、胡',
    animations: '动画效果',
    tileSize: '牌面大小',
    tileSizes: ['小', '中', '大'],
  },
  rulesPage: {
    entry: '规则',
    pageTitle: '规则与番型',
    patternsTitle: '番型（胡牌时可以叠加）',
    rulesTitle: '血战到底怎么玩',
  },
  review: {
    title: '复盘点评',
    none: '这一局的出牌没有明显失误 👍',
    hint: '点一条跳到那一步',
    chip: (step: number, played: string, better: string) => `第 ${step} 步：${played} → ${better}`,
    shanten: (played: string, better: string) => `打 ${played} 让手牌离听牌更远了，打 ${better} 更好`,
    acceptance: (played: string, better: string, a: number, b: number) => `打 ${better} 还能进 ${b} 张有效牌，打 ${played} 只剩 ${a} 张`,
  },
  replay: {
    title: (i: number) => `回放 · 第 ${i + 1} 局`,
    start: '开局',
    step: (i: number, n: number) => `${i} / ${n}`,
    play: '▶ 播放',
    pause: '⏸ 暂停',
    swap: (name: string) => `${name} 换三张`,
    dingque: (name: string, suit: string) => `${name} 定缺${suit}`,
    discard: (name: string, tile: string) => `${name} 打出 ${tile}`,
    pong: (name: string) => `${name} 碰`,
    kong: (name: string) => `${name} 杠`,
    selfKong: (name: string, tile: string) => `${name} 杠 ${tile}`,
    hu: (name: string) => `${name} 胡`,
    zimo: (name: string) => `${name} 自摸`,
    pass: (name: string) => `${name} 过`,
  },
  autoMenu: '自动',
  autoWin: '自动胡牌',
  autoNoClaims: '不碰不杠（胡牌仍会询问）',
  autoTsumogiri: '听牌后自动打出摸到的牌',
  trackerTitle: '还没出现的牌',
  trackerNote: '只算你看得到的牌：自己的手牌、所有人的弃牌和碰杠',
  soundLabel: (on: boolean): string => (on ? '音效' : '静音'),
  patternFan: (n: number) => `${n} 番`,
  maxFanPattern: '满番',
  selfDrawBonus: '加一份底分',
  fanCapped: (n: number) => `封顶 ${n} 番`,
  paysEach: (n: number) => `其余每家付 ${n}`,
  paysOne: (name: string, n: number) => `${name} 付 ${n}`,
  paymentExplain: {
    directKong: (from: string, to: string, n: number) => `刮风：${to} 明杠，${from} 付 ${n}`,
    addedKong: (from: string, to: string, n: number) => `刮风：${to} 补杠，${from} 付 ${n}`,
    concealedKong: (from: string, to: string, n: number) => `下雨：${to} 暗杠，${from} 付 ${n}`,
    callTransfer: (from: string, to: string, n: number) => `呼叫转移：${from} 杠后点炮，杠钱 ${n} 转给 ${to}`,
    huaZhu: (from: string, to: string, n: number) => `查花猪：${from} 流局时手里还有三门牌，赔给 ${to} ${n}`,
    daJiao: (from: string, to: string, n: number) => `查大叫：${from} 流局时没听牌，赔给听牌的 ${to} ${n}`,
    kongRefund: (from: string, to: string, n: number) => `退税：${from} 流局时没听牌，退还杠钱 ${n} 给 ${to}`,
  } as Record<string, (from: string, to: string, n: number) => string>,
  tips: {
    swap: '换三张：选三张同一花色的牌换给别人。已经帮你选好了，直接点「确认换牌」也行。',
    dingque: '定缺：选一门不要的花色，这门牌要全部打掉才能胡。一般选张数最少的那门。',
    discard: '轮到你出牌：点一张牌选中，再点一次就打出去，也可以把牌往上滑。',
    claim: '别人打出的这张牌你用得上：可以碰、杠或胡，不要就点「过」。',
    voidFirst: '手里还有缺门的牌，要先把它们打掉。',
    win: '可以胡了！血战到底：你胡牌后，剩下的人会接着打，直到只剩一家。',
    gotIt: '知道了',
  },
  sound: { title: '声音', effects: '音效', music: '音乐', on: '开', off: '关' },
  language: { title: '语言', zh: '中文', en: 'English' },
  tutorial: {
    title: '新手教程',
    subtitle: '6 节小课，每节一两分钟，在真实牌桌上一步步跟着做。不联网也能学。',
    back: '返回',
    next: '下一步',
    continue: '继续',
    lessonDone: '这一课学完了！',
    entry: '新手教程',
    firstTime: '第一次玩四川麻将？花 5 分钟学一下吧',
    fromLogin: '先看看新手教程',
  },
  chat: '聊天',
  report: '举报',
  reported: '已举报',
  chatPlaceholder: '说点什么…',
  send: '发送',
  toTable: '整桌',
  quickPhrases: '快捷语',
  stickers: '表情',
  close: '关闭',
  aiBadge: 'AI',
  banter: '牌友嘴碎程度',
  banterLevels: { mild: '温和', spicy: '毒舌', quiet: '安静' } as Record<string, string>,
  banterHint: {
    mild: '友好调侃，不嘲讽你',
    spicy: '斗嘴、嘲讽、阴阳怪气（不越界）',
    quiet: '只用表情和简短反应',
  } as Record<string, string>,
  // Accounts and economy (Phase 3)
  login: {
    title: '登录',
    guest: '游客登录',
    guestTrial: '游客试玩（每 15 天 1 小时）',
    apple: '通过 Apple 登录',
    google: '通过 Google 登录',
    wechat: '微信登录',
    phone: '手机号登录',
    phonePlaceholder: '手机号',
    codePlaceholder: '验证码',
    sendCode: '获取验证码',
    resend: (s: number) => `${s} 秒后重发`,
    submit: '登录',
    unavailable: '当前版本暂不支持此登录方式',
    privacy: '登录即表示同意《用户协议》和《隐私政策》',
  },
  loginErrors: {
    network: '连接服务器失败，请稍后再试',
    invalidPhone: '手机号格式不正确',
    invalidCode: '验证码错误或已过期',
    tooManyAttempts: '尝试次数过多，请重新获取验证码',
    rateLimited: '请求太频繁，请稍后再试',
    invalidToken: '登录凭证无效，请重试',
    notConfigured: '服务器未配置此登录方式',
    methodUnavailable: '当前地区不支持此登录方式',
    suspended: '账号已被暂停使用',
    identityInUse: '该账号已绑定到另一个游戏账号',
    nicknameRejected: '昵称不可用',
    serverError: '服务器出错了',
  } as Record<string, string>,
  realName: {
    title: '实名认证',
    hint: '根据国家规定，游戏账号须完成实名认证。身份证号仅用于认证，不会公开。',
    name: '真实姓名',
    idNumber: '身份证号',
    submit: '提交认证',
    invalid: '身份证号无效',
    failed: '认证未通过，请核对信息',
  },
  coins: '金币',
  dailyReward: '每日奖励',
  claim: (n: number) => `领取 ${n.toLocaleString()} 金币`,
  claimed: '今天已领取',
  rewardDay: (d: number) => `第 ${d} 天`,
  rewardNote: '错过的天数不会清零，领完一轮重新开始。',
  tables: '选择场次',
  brand: '四川麻将',
  brandSub: '血战到底',
  quickStart: '快速开始',
  needMore: (n: number) => `还差 ${n.toLocaleString()} 金币`,
  tutorialProgress: (done: number, total: number) => (done >= total ? '新手教程 已学完' : `新手教程 ${done}/${total}`),
  rewardReady: '今日奖励可领取',
  rewardTaken: '今日奖励已领取',
  recommended: '推荐',
  continueLesson: '继续学习',
  winds: ['东', '南', '西', '北'],
  tableNames: { practice: '练习场', low: '初级场', mid: '中级场', high: '高级场' } as Record<string, string>,
  baseScoreN: (n: number) => `底分 ${n}`,
  minCoinsN: (n: number) => `准入 ${n.toLocaleString()}`,
  noCoins: '不结算金币',
  privateRoom: '私人房',
  privateRoomHint: '免费创建，自定义底分、局数和规则',
  privateCreate: '开房',
  inviteCode: '房号',
  maxBaseHint: (n: number) => `底分最高 ${n.toLocaleString()}（余额的 1%），0 为不结算`,
  rules: {
    huanSanZhang: '换三张',
    callTransfer: '呼叫转移',
    selfDrawFan: '自摸加番（关：自摸加底）',
    maxFan: '封顶番数',
    xueliu: '血流成河（胡了接着打，可以多次胡）',
  },
  modeName: (xueliu: boolean): string => (xueliu ? '血流成河' : '血战到底'),
  winTimes: (n: number) => `胡 ×${n}`,
  startRejected: {
    unknownTable: '场次不存在',
    insufficientCoins: '金币不足，无法进入该场次',
    baseTooHigh: '底分超出上限',
    invalidOptions: '房间设置无效',
    realNameRequired: '请先完成实名认证',
    minorTimeLimit: '未成年人仅可在周五、周六、周日和法定节假日 20:00–21:00 游戏',
    guestTrialOver: '游客试玩时间已用完，请登录后继续',
  } as Record<string, string>,
  minorLimit: (until: number | null) => (until ? `未成年人游戏时间至 ${new Date(until).toLocaleTimeString().slice(0, 5)}` : '未成年人仅可在周五、周六、周日和法定节假日 20:00–21:00 游戏'),
  guestLimit: (until: number | null) => (until ? `游客试玩至 ${new Date(until).toLocaleTimeString().slice(0, 5)}` : '游客试玩时间已用完，请登录正式账号'),
  limitEnding: '游戏时间即将结束，到时将由系统托管打完本局',
  crashTitle: '出了点问题',
  crashText: '应用遇到了一个错误，已自动上报。点下面的按钮回到游戏。',
  crashRetry: '重新加载',
  legal: { privacy: '《隐私政策》', terms: '《用户协议》', sdks: '《第三方 SDK 清单》' },
  consent: {
    title: '欢迎来到四川麻将',
    body: '在开始之前，请阅读《用户协议》和《隐私政策》。我们会收集账号标识、游戏记录和聊天内容来提供游戏服务；牌桌上的 AI 角色由大模型生成对话。我们不出售你的个人信息，不做跨应用追踪。',
    agree: '同意并继续',
    decline: '不同意',
    declined: '不同意的话无法登录和保存进度。你仍然可以离线学习新手教程，或者重新阅读后再决定。',
    reread: '重新阅读',
  },
  healthAdvice: '健康游戏忠告：抵制不良游戏，拒绝盗版游戏。注意自我保护，谨防受骗上当。适度游戏益脑，沉迷游戏伤身。合理安排时间，享受健康生活。',
  ageRating: (age: string) => `适龄提示：${age}`,
  about: {
    title: '关于',
    version: (v: string) => `版本 ${v}`,
    ai: '牌桌上的其他玩家都是 AI 角色，他们的发言由人工智能生成，仅供娱乐。遇到不当内容请长按气泡举报。',
    coins: '金币仅用于游戏娱乐，不能购买、兑换或转让。',
    icp: (n: string) => `ICP 备案号：${n}`,
    appFiling: (n: string) => `APP 备案号：${n}`,
  },
  account: '账号',
  nickname: '昵称',
  save: '保存',
  avatar: '头像',
  linked: '已绑定',
  link: '绑定',
  linkHint: '游客数据保存在本机，卸载后会丢失。绑定账号可永久保存。',
  linkConflict: '该登录方式已属于另一个游戏账号。要切换过去，请先退出当前账号，再用它登录（当前账号不会受影响）。',
  methodNames: { guest: '游客', apple: 'Apple', google: 'Google', phone: '手机号', wechat: '微信' } as Record<string, string>,
  history: '金币记录',
  ledgerTypes: { startingCoins: '新手金币', handSettlement: '牌局结算', loginReward: '每日奖励', taskReward: '每日任务（已停用）', achievementReward: '成就奖励', adminAdjustment: '客服调整' } as Record<string, string>,
  logout: '退出登录',
  deleteAccount: '注销账号',
  deleteConfirmTitle: '确定注销账号？',
  deleteConfirmBody: '注销后，你的资料、金币和与 AI 牌友的记忆都会被删除，无法恢复。',
  handCoins: (n: number) => `本局金币 ${n > 0 ? '+' : ''}${n.toLocaleString()}`,
  gameCoins: (n: number) => `本场金币 ${n > 0 ? '+' : ''}${n.toLocaleString()}`,
  awayResult: '你离开后，上一场牌局已由系统托管打完',
  ok: '知道了',
  chatRejected: {
    blocked: '消息未发送',
    rateLimited: '发得太快了，歇一会儿',
    suspended: '聊天功能暂时不可用',
    tooLong: '消息太长了',
    notInGame: '不在牌局中',
  } as Record<string, string>,
};

export type Strings = typeof zh;

const en: Strings = {
  appTitle: 'Sichuan Mahjong · Bloody Battle',
  start: 'Start',
  hands: 'Hands',
  baseScore: 'Base score',
  connecting: 'Connecting to the server…',
  offline: "Can't reach the server, retrying…",
  reconnecting: 'Reconnecting…',
  swapHint: 'Suggested three tiles are selected — tap to change (one suit)',
  swapConfirm: 'Swap',
  swapWaiting: 'Waiting for the others to swap…',
  dingqueHint: 'Pick the suit you will give up (void suit)',
  dingqueWaiting: 'Waiting for the others to pick their void suit…',
  voidSuit: (suit: string) => `Void: ${suit}`,
  tileShort: (rank: number, suit: string) => `${rank} ${suit}`,
  pong: 'Pong',
  kong: 'Kong',
  hu: 'Win',
  zimo: 'Self-draw',
  pass: 'Pass',
  discard: 'Discard',
  discardHint: 'Tap a tile twice or swipe up to discard',
  voidFirst: 'Discard your void-suit tiles first',
  autoPlayOn: 'Auto-play on — tap to take back control',
  autoPlay: 'Auto',
  skipToResults: 'Skip to results',
  leave: 'Leave',
  leaveConfirmTitle: 'Leave the game?',
  leaveConfirmBody: 'Auto-play will finish the game for you and coins settle as usual.',
  cancel: 'Cancel',
  confirm: 'OK',
  wall: 'Wall',
  dealer: 'Dealer',
  tilesInHand: (n: number) => `${n} tiles`,
  robbed: 'Robbed!',
  handResult: 'Hand result',
  gameResult: 'Game result',
  nextHand: 'Next hand',
  newGame: 'Play again',
  backHome: 'Back to lobby',
  threeWon: 'Three players won',
  wallExhausted: 'Wall exhausted',
  huaZhu: 'Flower Pig',
  ready: 'Ready',
  notReady: 'Not ready',
  me: ' (me)',
  dealtInBy: (name: string) => ` (from ${name})`,
  fan: (n: number) => `${n} fan`,
  colon: ': ',
  listSeparator: '  ',
  hand: (i: number, n: number) => `Hand ${i + 1} / ${n}`,
  swapDirection: { clockwise: 'Swap clockwise', counterClockwise: 'Swap counter-clockwise', opposite: 'Swap across' },
  timeoutWarning: (s: number) => `Auto-move in ${s}s`,
  waiting: 'Waiting on',
  discardedBy: (name: string) => `${name} discards`,
  waitingNone: 'Ready, but every tile you need is gone',
  tilesLeft: (n: number) => `${n} left`,
  ifDiscard: 'Discard this →',
  shantenAfter: (n: number) => `${n} away from ready`,
  hint: '💡 Hint',
  hintClaim: (what: string) => `Suggested: ${what}`,
  tracker: 'Tracker',
  record: {
    entry: 'Stats',
    title: 'Stats and replays',
    games: 'Games',
    hands: 'Hands',
    winRate: 'Win rate',
    selfDraws: 'Self-draws',
    dealInRate: 'Deal-in rate',
    bestFan: 'Best fan',
    recent: 'Recent hands (tap one to replay)',
    regulars: 'Table regulars',
    regularsHint: 'AI characters you have played with',
    together: (hands: number) => `${hands} hands together`,
    headToHead: (mine: number, theirs: number) => `You won ${mine} · they won ${theirs}`,
    dealIns: (mine: number, theirs: number) => `You fed them ${mine} · they fed you ${theirs}`,
    bond: (hands: number, rival: boolean) => (rival ? 'Nemesis' : hands >= 40 ? 'Old friend' : hands >= 8 ? 'Regular' : 'New face'),
    empty: 'No finished hands yet',
    won: (fan: number, selfDraw: boolean) => `${selfDraw ? 'Self-draw' : 'Win'} · ${fan} fan`,
    handOf: (i: number) => `Hand ${i + 1}`,
    back: 'Back',
    loadFailed: "Couldn't load. Try again later.",
  },
  bindReminder: {
    text: 'Guest progress (coins, rank, achievements) is lost if you change phones or clear app data. Link a sign-in method to keep it.',
    bind: 'Link account',
    later: 'Not now',
  },
  fairness: {
    verified: '🔒 Deal verified: fixed before play, never changed',
    failed: '⚠️ Deal check failed. Please contact support.',
    details: 'Show the proof',
    hide: 'Hide',
    commitment: (c: string) => `Published before the deal: ${c}`,
    revealed: (seed: number, salt: string) => `Revealed after the hand: ${seed} · ${salt}`,
    how: 'Before the deal we publish sha256(seed:salt); after the hand we reveal the seed. The seed re-deals the whole wall, so a matching digest proves the tiles were fixed before play and never changed.',
    replay: (seed: number) => `🔒 Dealt from seed ${seed}; this replay re-deals it from that seed`,
  },
  rank: {
    tiers: { novice: 'Novice', adept: 'Adept', expert: 'Expert', master: 'Master', saint: 'Grandmaster' } as Record<string, string>,
    label: (tier: string, points: number) => `${tier} · ${points} pts`,
    toNext: (n: number) => `${n} pts to the next rank`,
    result: (place: number, change: number) => `Place ${place} · rank ${change >= 0 ? '+' : ''}${change}`,
    promoted: (tier: string) => `Promoted to ${tier}!`,
    note: 'Only coin tables (Beginner and up) count for rank',
  },
  friend: {
    entry: 'Friends',
    hint: 'Play with friends, points only',
    title: 'Friend room',
    intro: 'Sit at one table with friends. Points only: no coins, no rank. Empty seats are filled by AI.',
    createTitle: 'Open a room',
    create: 'Create',
    joinTitle: "Enter a friend's room number",
    join: 'Join',
    waitingTitle: 'Waiting for friends',
    roomNumber: 'Room number',
    shareHint: 'Share the invite link and friends join with one tap, or tell them the number',
    aiFill: 'AI fills in',
    host: 'Host',
    offline: 'offline',
    rules: (hands: number, mode: string) => `${mode} · ${hands} hands · points only, no coins · AI fills empty seats`,
    leave: 'Leave room',
    start: 'Start',
    startWithAi: 'Start with AI',
    startJustUs: (n: number) => `Just us ${n} (two suits)`,
    needFriend: 'Waiting for a friend',
    waitingHost: 'Waiting for the host to start…',
    tableName: 'Friend room',
    readyWaiting: 'Ready, waiting for the others…',
    share: '📤 Share invite',
    copied: 'Invite copied: paste it to your friends',
    shareFailed: "Couldn't open sharing; tell your friends the number",
    inviteText: (code: string, url: string) => `Join my Sichuan Mahjong table! Room ${code}
Tap to join: ${url}`,
    rejected: {
      notFound: 'No room with that number',
      full: 'That room is full',
      inGame: "You're in a game: finish it first",
      notHost: 'Only the host can start',
      needFriend: 'At least one friend has to join first',
      blocked: (name: string) => `${name} can't play right now (play-time limit or real-name check)`,
    } as Record<string, string | ((name: string) => string)>,
  },
  achievements: {
    entry: 'Achievements',
    title: 'Achievements',
    intro: 'They unlock as you play and pay out by themselves: no tasks, no daily check-ins.',
    loginTitle: 'Login reward (paid automatically on your first visit each day)',
    listTitle: 'Achievements (one reward each)',
    claim: (n: number) => `Claim ${n}`,
    earned: (names: string, total: number) => `🏆 ${names}  🪙 +${total}`,
    paid: 'Paid',
    locked: 'Not yet',
    names: {
      login: "Today's login reward",
      firstWin: 'First win',
      firstSelfDraw: 'First self-draw',
      firstKong: 'First kong',
      duiDuiHu: 'Win with all pongs',
      qiDui: 'Win with seven pairs',
      qingYiSe: 'Win with a pure suit',
      gangShangHua: 'Win on a kong draw',
      bigWin: 'Win with 3+ fan',
      wins10: 'Win 10 hands',
      wins50: 'Win 50 hands',
      games10: 'Finish 10 games',
    },
  },
  settings: {
    entry: 'Settings',
    title: 'Settings',
    fastPace: 'Quick pace',
    fastPaceHint: 'AI players move almost without pausing',
    voice: 'Announce pong, kong and wins aloud',
    animations: 'Animations',
    tileSize: 'Tile size',
    tileSizes: ['Small', 'Medium', 'Large'],
  },
  rulesPage: {
    entry: 'Rules',
    pageTitle: 'Rules and patterns',
    patternsTitle: 'Patterns (they stack)',
    rulesTitle: 'How bloody battle works',
  },
  review: {
    title: 'Review',
    none: 'No clear mistakes in your discards this hand 👍',
    hint: 'Tap one to jump to that move',
    chip: (step: number, played: string, better: string) => `Move ${step}: ${played} → ${better}`,
    shanten: (played: string, better: string) => `Discarding ${played} set the hand back; ${better} was better`,
    acceptance: (played: string, better: string, a: number, b: number) => `Discarding ${better} keeps ${b} useful draws; ${played} leaves only ${a}`,
  },
  replay: {
    title: (i: number) => `Replay · hand ${i + 1}`,
    start: 'Deal',
    step: (i: number, n: number) => `${i} / ${n}`,
    play: '▶ Play',
    pause: '⏸ Pause',
    swap: (name: string) => `${name} swaps three`,
    dingque: (name: string, suit: string) => `${name} voids ${suit}`,
    discard: (name: string, tile: string) => `${name} discards ${tile}`,
    pong: (name: string) => `${name} pongs`,
    kong: (name: string) => `${name} kongs`,
    selfKong: (name: string, tile: string) => `${name} kongs ${tile}`,
    hu: (name: string) => `${name} wins`,
    zimo: (name: string) => `${name} self-draws`,
    pass: (name: string) => `${name} passes`,
  },
  autoMenu: 'Auto',
  autoWin: 'Declare wins automatically',
  autoNoClaims: 'Skip pong and kong (wins still ask)',
  autoTsumogiri: "When ready, discard each drawn tile that doesn't win",
  trackerTitle: 'Tiles not seen yet',
  trackerNote: 'Counts only what you can see: your hand, every pond and every meld',
  soundLabel: (on: boolean) => (on ? 'Sound' : 'Muted'),
  patternFan: (n: number) => `${n} fan`,
  maxFanPattern: 'max fan',
  selfDrawBonus: 'plus one base score',
  fanCapped: (n: number) => `capped at ${n} fan`,
  paysEach: (n: number) => `each other player pays ${n}`,
  paysOne: (name: string, n: number) => `${name} pays ${n}`,
  paymentExplain: {
    directKong: (from: string, to: string, n: number) => `Exposed kong by ${to}: ${from} pays ${n}`,
    addedKong: (from: string, to: string, n: number) => `Added kong by ${to}: ${from} pays ${n}`,
    concealedKong: (from: string, to: string, n: number) => `Concealed kong by ${to}: ${from} pays ${n}`,
    callTransfer: (from: string, to: string, n: number) => `Kong transfer: ${from} dealt in right after a kong, passing ${n} of kong money to ${to}`,
    huaZhu: (from: string, to: string, n: number) => `Flower pig: ${from} still held three suits at the draw, pays ${to} ${n}`,
    daJiao: (from: string, to: string, n: number) => `Not ready: ${from} wasn't ready at the draw, pays ${to} ${n}`,
    kongRefund: (from: string, to: string, n: number) => `Kong refund: ${from} wasn't ready at the draw, returns ${n} to ${to}`,
  },
  tips: {
    swap: 'Swap three: pass three tiles of one suit to another player. They are already picked for you, so you can just confirm.',
    dingque: 'Void suit: pick a suit to give up. You must discard all of it before you can win. Usually pick the suit you hold fewest of.',
    discard: 'Your turn: tap a tile to select it, tap it again to discard. You can also swipe it up.',
    claim: 'You can use this discard: pong, kong or win with it, or pass.',
    voidFirst: 'You still hold void-suit tiles. Discard those first.',
    win: 'You can win! Bloody battle: after you win, the others keep playing until only one is left.',
    gotIt: 'Got it',
  },
  sound: { title: 'Sound', effects: 'Effects', music: 'Music', on: 'on', off: 'off' },
  language: { title: 'Language', zh: '中文', en: 'English' },
  tutorial: {
    title: 'Tutorial',
    subtitle: 'Six short lessons, a minute or two each, played step by step on a real table. Works offline.',
    back: 'Back',
    next: 'Next',
    continue: 'Continue',
    lessonDone: 'Lesson complete!',
    entry: 'Tutorial',
    firstTime: 'New to Sichuan Mahjong? Learn it in 5 minutes',
    fromLogin: 'Try the tutorial first',
  },
  chat: 'Chat',
  report: 'Report',
  reported: 'Reported',
  chatPlaceholder: 'Say something…',
  send: 'Send',
  toTable: 'Everyone',
  quickPhrases: 'Phrases',
  stickers: 'Stickers',
  close: 'Close',
  aiBadge: 'AI',
  banter: 'Table talk',
  banterLevels: { mild: 'Friendly', spicy: 'Spicy', quiet: 'Quiet' },
  banterHint: {
    mild: 'Friendly teasing, never at your expense',
    spicy: 'Trash talk and sarcasm (within limits)',
    quiet: 'Only stickers and short reactions',
  },
  login: {
    title: 'Sign in',
    guest: 'Play as guest',
    guestTrial: 'Guest trial (1 hour per 15 days)',
    apple: 'Sign in with Apple',
    google: 'Sign in with Google',
    wechat: 'Sign in with WeChat',
    phone: 'Phone number',
    phonePlaceholder: 'Phone number',
    codePlaceholder: 'Code',
    sendCode: 'Send code',
    resend: (s: number) => `Resend in ${s}s`,
    submit: 'Sign in',
    unavailable: 'This sign-in method is not available in this version',
    privacy: 'By signing in you agree to the Terms of Service and Privacy Policy',
  },
  loginErrors: {
    network: "Couldn't reach the server, please try again later",
    invalidPhone: 'Invalid phone number',
    invalidCode: 'Wrong or expired code',
    tooManyAttempts: 'Too many attempts, request a new code',
    rateLimited: 'Too many requests, please try again later',
    invalidToken: 'Sign-in failed, please try again',
    notConfigured: 'This sign-in method is not set up on the server',
    methodUnavailable: 'This sign-in method is not available in your region',
    suspended: 'This account has been suspended',
    identityInUse: 'This sign-in is already linked to another game account',
    nicknameRejected: 'That nickname is not allowed',
    serverError: 'Something went wrong on the server',
  },
  realName: {
    title: 'Identity verification',
    hint: 'Game accounts must complete real-name verification. Your ID number is only used for verification.',
    name: 'Full name',
    idNumber: 'ID number',
    submit: 'Verify',
    invalid: 'Invalid ID number',
    failed: 'Verification failed, please check your details',
  },
  coins: 'Coins',
  dailyReward: 'Daily reward',
  claim: (n: number) => `Claim ${n.toLocaleString()} coins`,
  claimed: 'Claimed today',
  rewardDay: (d: number) => `Day ${d}`,
  rewardNote: "Missed days don't reset your progress; the cycle restarts after the last day.",
  tables: 'Choose a table',
  brand: 'Sichuan Mahjong',
  brandSub: 'Bloody Battle',
  quickStart: 'Quick start',
  needMore: (n: number) => `Need ${n.toLocaleString()} more coins`,
  tutorialProgress: (done: number, total: number) => (done >= total ? 'Tutorial complete' : `Tutorial ${done}/${total}`),
  rewardReady: "Today's reward is ready",
  rewardTaken: "Today's reward claimed",
  recommended: 'Recommended',
  continueLesson: 'Continue',
  winds: ['E', 'S', 'W', 'N'],
  tableNames: { practice: 'Practice', low: 'Beginner', mid: 'Intermediate', high: 'High Roller' },
  baseScoreN: (n: number) => `Base ${n}`,
  minCoinsN: (n: number) => `Min ${n.toLocaleString()}`,
  noCoins: 'No coins at stake',
  privateRoom: 'Private room',
  privateRoomHint: 'Free to create: choose base score, hands and rules',
  privateCreate: 'Create',
  inviteCode: 'Room',
  maxBaseHint: (n: number) => `Base score up to ${n.toLocaleString()} (1% of your coins); 0 means no coins`,
  rules: {
    huanSanZhang: 'Swap three',
    callTransfer: 'Kong transfer',
    selfDrawFan: 'Self-draw adds a fan (off: adds base)',
    maxFan: 'Fan cap',
    xueliu: 'Endless river (keep playing after a win, win again)',
  },
  modeName: (xueliu: boolean): string => (xueliu ? 'Endless river' : 'Bloody battle'),
  winTimes: (n: number) => `Won ×${n}`,
  startRejected: {
    unknownTable: 'That table does not exist',
    insufficientCoins: 'Not enough coins for this table',
    baseTooHigh: 'Base score is too high',
    invalidOptions: 'Invalid room settings',
    realNameRequired: 'Please complete identity verification first',
    minorTimeLimit: 'Minors may only play 20:00–21:00 on Fridays, weekends and public holidays',
    guestTrialOver: 'Your guest trial is over; sign in to keep playing',
  },
  minorLimit: (until: number | null) => (until ? `Minor play time until ${new Date(until).toLocaleTimeString().slice(0, 5)}` : 'Minors may only play 20:00–21:00 on Fridays, weekends and public holidays'),
  guestLimit: (until: number | null) => (until ? `Guest trial until ${new Date(until).toLocaleTimeString().slice(0, 5)}` : 'Guest trial is over; please sign in'),
  limitEnding: 'Play time is almost over; auto-play will finish the game',
  crashTitle: 'Something went wrong',
  crashText: 'The app hit an error and reported it automatically. Tap below to get back to the game.',
  crashRetry: 'Reload',
  legal: { privacy: 'Privacy Policy', terms: 'Terms of Service', sdks: 'Third-party SDKs' },
  consent: {
    title: 'Welcome to Sichuan Mahjong',
    body: 'Before you start, please read the Terms of Service and Privacy Policy. We collect account identifiers, game records and chat messages to run the game; the AI players at the table talk using a large language model. We never sell your personal information and do not track you across apps.',
    agree: 'Agree and continue',
    decline: 'Decline',
    declined: "Without agreeing you can't sign in or save progress. You can still take the offline tutorial, or read the documents again and decide.",
    reread: 'Read again',
  },
  healthAdvice: '',
  ageRating: (age: string) => `Age rating: ${age}`,
  about: {
    title: 'About',
    version: (v: string) => `Version ${v}`,
    ai: 'The other players at the table are AI characters. What they say is generated by AI, for fun only. Long-press a speech bubble to report anything inappropriate.',
    coins: 'Coins are for fun only: they cannot be bought, exchanged or transferred.',
    icp: (n: string) => `ICP: ${n}`,
    appFiling: (n: string) => `App filing: ${n}`,
  },
  account: 'Account',
  nickname: 'Nickname',
  save: 'Save',
  avatar: 'Avatar',
  linked: 'Linked',
  link: 'Link',
  linkHint: 'Guest data lives on this device and is lost if you uninstall. Link an account to keep it.',
  linkConflict: 'That sign-in already belongs to another game account. To switch, sign out first and sign in with it (this account is not affected).',
  methodNames: { guest: 'Guest', apple: 'Apple', google: 'Google', phone: 'Phone', wechat: 'WeChat' },
  history: 'Coin history',
  ledgerTypes: { startingCoins: 'Welcome coins', handSettlement: 'Hand settlement', loginReward: 'Daily reward', taskReward: 'Daily task (retired)', achievementReward: 'Achievement', adminAdjustment: 'Support adjustment' },
  logout: 'Sign out',
  deleteAccount: 'Delete account',
  deleteConfirmTitle: 'Delete your account?',
  deleteConfirmBody: 'Your profile, coins and memories with the AI players will be deleted. This cannot be undone.',
  handCoins: (n: number) => `This hand ${n > 0 ? '+' : ''}${n.toLocaleString()} coins`,
  gameCoins: (n: number) => `This game ${n > 0 ? '+' : ''}${n.toLocaleString()} coins`,
  awayResult: 'While you were away, auto-play finished your last game',
  ok: 'OK',
  chatRejected: {
    blocked: 'Message not sent',
    rateLimited: "You're sending too fast, take a breather",
    suspended: 'Chat is temporarily unavailable',
    tooLong: 'Message is too long',
    notInGame: 'Not in a game',
  },
};

export const SUIT_NAMES: Record<Suit, string> = { ...zhNames.suits };
export const TILE_SUITS: Record<Suit, string> = { ...zhNames.tileSuits };
export const RANK_NAMES: string[] = [...zhNames.ranks];
/** Chinese numerals, printed on Characters tiles in every language. */
export const RANK_NAMES_ZH: readonly string[] = [...zhNames.ranks];
export const PATTERN_NAMES: Record<Pattern, string> = { ...zhNames.patterns };
export const PAYMENT_NAMES: Record<string, string> = { ...zhNames.payments };
export const T: Strings = { ...zh };

let current: Locale = 'zh';

export function getLocale(): Locale {
  return current;
}

/** Switches every catalog in place; callers re-render (the app root remounts on change). */
export function setLocale(locale: Locale): void {
  current = locale;
  const names = locale === 'en' ? enNames : zhNames;
  Object.assign(T, locale === 'en' ? en : zh);
  Object.assign(SUIT_NAMES, names.suits);
  Object.assign(TILE_SUITS, names.tileSuits);
  RANK_NAMES.splice(0, RANK_NAMES.length, ...names.ranks);
  Object.assign(PATTERN_NAMES, names.patterns);
  Object.assign(PAYMENT_NAMES, names.payments);
}

/** Table names: the server's (admin-editable, Chinese) names, or the English names in English. */
export function tableName(stake: { kind?: string; tableId?: string; id?: string; name: string }): string {
  if (stake.kind === 'private') return T.privateRoom;
  if (stake.kind === 'friend') return T.friend.tableName;
  const id = stake.tableId ?? stake.id;
  return current === 'en' && id ? (T.tableNames[id] ?? stake.name) : stake.name;
}

/** Text that has both languages inline (tutorial scripts). */
export type Bilingual = { zh: string; en: string };
export const tr = (text: Bilingual): string => text[current];
